### ISSUE TITLE
[FEAT] - Replace Banner Image

### ISSUE THREAD

**Issue by sreekaransrinath** [nhcarrigan/nhcarrigan#13]
# Feature Request

## Is your feature request related to a problem? Please describe:

The profile banner is a bit low-res (not `crispy` enough hahah)

## Describe the solution you'd like

Try to upload a higher-res version of the banner.

## Additional context

![image](https://user-images.githubusercontent.com/50989977/116909926-80a4f980-ac62-11eb-80e2-28596111f299.png)

**Comment by nhcarrigan** [comment]
## Locked Issue

Thank you for opening this issue. We agree that this is a necessary fix, but unfortunately at this time the nature of the fix requires contribution from project staff. As such, we cannot open up this issue to contributions just yet. :)
