### ISSUE TITLE
[DOC] - Typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Dovonun** [nhcarrigan/nhcarrigan#16]
# Incorrect Documentation

## Describe the error

In CONTRIBUTING.md at the beginning of line 50, the first character is missing.

## Expected information

The first word of the line should be 'Now' instead of 'ow'.

**Comment by nhcarrigan** [comment]
Good catch!

**Comment by nhcarrigan** [comment]
Yep!

**Comment by dineshkumar12004** [comment]
Made pull request 😇
