### ISSUE TITLE
[DOC] - invalid contact link

### ISSUE THREAD

**Issue by RawandDev** [nhcarrigan/nhcarrigan#20]
### What is incorrect in the documentation?

I may be contacted through my [Chat Server](http://chat.nhcarrigan.com) or via [email form](https://www.nhcarrigan.com/contact).
The email form doesn't work since the https://www.nhcarrigan.com/contact is removed.

### What should that text say?

I may be contacted through my [Chat Server](http://chat.nhcarrigan.com) or via [platforms](https://www.nhcarrigan.com/#contact).
It is basically the same but instead of /contact link to /#contact.

### Additional information
I edited via email form to platforms since there is no email form there. I had no idea whether to choose platforms or social media so I chose platforms.
_No response_

**Comment by nhcarrigan** [comment]
We should change the text to:
```md
I may be contacted through my [chat server](https://chat.nhcarrigan.com) or [other social platforms](https://www.nhcarrigan.com/#contact).
```

**Comment by RawandDev** [comment]
I have created a PR for this issue #21
